version: '3'
services:
  nginx-eg1:
    image: nginx:latest
    ports:
      - "8443:8443"
    links:
      - web
    volumes:
      - ./server/nginx-eg1.conf:/etc/nginx/conf.d/default.conf
      - ./server:/config/tls
  nginx-eg2:
    image: nginx:latest
    ports:
      - "9443:9443"
    links:
      - web
    volumes:
      - ./server/nginx-eg2.conf:/etc/nginx/conf.d/default.conf
      - ./server:/config/tls
  web:
    image: nginxdemos/hello:plain-text
